global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'idontknowpumka@gmail.com'
  smtp_auth_username: 'idontknowpumka@gmail.com'
  smtp_auth_password: 'jpwq reqv npoz jvvg'
  smtp_require_tls: true

route:
  group_by:
    - alertname
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: gmail-alerts

receivers:
  - name: gmail-alerts
    email_configs:
      - to: 'idontknowpumka@gmail.com'
        send_resolved: true
