apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: devjops-backend
  namespace: monitoring

spec:
  selector:
    matchLabels:
      app: backend

  namespaceSelector:
    matchNames:
      - devjops

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
